/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./app/**/*.{js,jsx,ts,tsx}', './components/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        background: "#0A0F1E",
        surface: "#111827",
        "surface-light": "#1E293B",
        border: "#1E293B",
        primary: "#3B82F6",
        auto: "#EF4444",
        transition: "#F59E0B",
        teleop: "#22C55E",
        "text-primary": "#F5F5F5",
        "text-secondary": "#9CA3AF",
        accent: {
          green: "#10B981",
          blue: "#3B82F6",
          yellow: "#F59E0B",
          purple: "#8B5CF6",
        },
        // Stitch design system tokens
        "surface-container-low": "#0f131d",
        "surface-container": "#151a24",
        "surface-container-high": "#1b202b",
        "surface-container-highest": "#202632",
        "on-surface": "#e8eaf7",
        "on-surface-variant": "#a8abb6",
        "stitch-primary": "#84adff",
        "on-stitch-primary": "#002d64",
        "secondary-container": "#785900",
        "on-secondary-container": "#fff6ec",
        "stitch-secondary": "#fdc003",
        "tertiary": "#a1faff",
        "stitch-error": "#ff6e84",
        "on-stitch-error": "#490013",
        "outline-variant": "#444852",
        // Additional Stitch tokens
        "on-primary-fixed": "#000000",
        "surface-dim": "#0a0e16",
        "error-container": "#a70138",
        "on-error-container": "#ffb2b9",
        "surface-bright": "#262c39",
        "tertiary-dim": "#00e5ee",
        // Stitch shorthand aliases (match Stitch HTML token names)
        "primary": "#84adff",
        "on-primary": "#002d64",
        "secondary": "#fdc003",
        "on-secondary": "#553e00",
        "error": "#ff6e84",
        "on-error": "#490013",
      },
    },
  },
  plugins: [require('@iconify/tailwind').addDynamicIconSelectors()],
};
